### ISSUE TITLE
你好 我想问一下这个为什么没有数据变化 文章页面是有变化的

### ISSUE THREAD

**Issue by zjrwtx** [HerryLo/uniapp-wxapp#2]
![image](https://user-images.githubusercontent.com/86822589/213173027-29b3e018-f863-4ccd-aee5-195821b572b7.png)
![image](https://user-images.githubusercontent.com/86822589/213173212-4cc2010b-c91e-459f-8361-77863e97334b.png)

**Comment by HerryLo** [comment]
首页的文章列表数据是写死的，固定的

**Comment by HerryLo** [comment]
你可以修改为你自己想要的
